### ISSUE TITLE
v1.0 Roadmap

### ISSUE THREAD

**Issue by kaylendog** [kaylendog/consul-oxide#6]
### `/acl`

- [x] `PUT /acl/bootstrap`
- [x] `GET /acl/replication`
- [x] `/acl/login`
 
The following endpoints will not be added as they were depreacted in Consul v1.11:
- `POST /acl/rules/translate`
- `GET /acl/rules/translate/:accessor_id`

#### `/acl/token`

- [x] `PUT /acl/token`
- [x] `GET /acl/token/:AccessorID`
- [x] `GET /acl/token/self`
- [x] `PUT /acl/token/:AccessorID`
- [x] `PUT /acl/token/:AccessorID`
- [x] `DELETE /acl/token/:AccessorID`
- [x] `GET /acl/tokens`

#### `/acl/policy/`

- [ ] `PUT /acl/policy`
- [ ] `GET /acl/policy/:id`
- [ ] `GET /acl/policy/name/:name`
- [ ] `PUT /acl/policy/:id`
- [ ] `DELETE /acl/policy/:id`
- [ ] `GET /acl/policies`

#### `/acl/role`

- [ ] `PUT /acl/role`
- [ ] `GET /acl/role/:id`
- [ ] `GET /acl/role/name/:name`
- [ ] `PUT /acl/role/:id`
- [ ] `DELETE /acl/role/:id`
- [ ] `GET /acl/roles`

#### `/acl/auth-method`

- [ ] `PUT /acl/auth-method`
- [ ] `GET /acl/auth-method/:name`
- [ ] `PUT /acl/auth-method/:name`
- [ ] `DELETE /acl/auth-method/:name`
- [ ] `GET /acl/auth-methods`

#### `/acl/binding-rule`

- [ ] `PUT /acl/binding-rule`
- [ ] `GET /acl/binding-rule/:id`
- [ ] `PUT /acl/binding-rule/:id`
- [ ] `DELETE /acl/binding-rule/:id`
- [ ] `GET /acl/binding-rules`

The following endpoints will not be added as they require Consul Enterprise:
- `POST /acl/oidc/auth-url`

### `/partition`

These endpoints will not be added as they require Consul Enterprise.

### `/agent/connect`

- [ ] `POST /agent/connect/authorize`
- [ ] `GET /agent/connect/ca/roots`
- [ ] `GET /agent/connect/ca/leaf/:service`

#### Renamed Methods
- [x] `Catalog::register` -> `Catalog::register_entity`
- [x] `Catalog::deregister` -> `Catalog::deregister_entity`
- [x] `Catalog::list_datacenter_nodes` -> `Catalog::list_nodes`
- [x] `Catalog::list_datacenter_services` -> `Catalog::list_services`

### `/peering`

Since this feature is only available in Consul v1.13 and later, it will not be implemented this release.

### `/config`

- [ ] `PUT /config`
- [ ] `GET /config/:kind/:name`
- [ ] `DELETE /config/:kind/:name`
- [ ] `GET /config/:kind`

### `/connect/intentions`

- [ ] `GET /connect/intentions`
- [ ] `GET /connect/intentions/exact`
- [ ] `PUT /connect/intentions/exact`
- [ ] `DELETE /connect/intentions/exact`
- [ ] `GET /connect/intentions/check`
- [ ] `GET /connect/intentions/match`

The following endpoints will not be implemented as they are deprecated:

- `GET /connect/intentions/:uuid`
- `PUT /connect/intentions/:uuid`
- `DELETE /connect/intentions/:uuid`

### `/coordinates`

- [ ] `GET /coordinate/datacenters`
- [ ] `GET /coordinate/nodes`
- [ ] `GET /coordinate/node/:node_name`
- [ ] `PUT /coordinate/update`

### `/discovery-chain`

This endpoint will not be implemented as it is primarily targeted for developers with low-level use cases.

### `/events`

- [ ] `PUT /event/fire/:name`
- [ ] `GET /event/list`

### `/health`

- [x] `GET /health/service/:service`
- [ ] `GET /health/node/:node`
- [ ] `GET /health/checks/:service`
- [ ] `GET /health/connect/:service`
- [ ] `GET /health/ingress/:service`
- [ ] `GET /health/state/:state`

#### `/operator/area`

These endpoints will not be added as they require Consul Enterprise.

#### `/operator/autopilot`

- [ ] `GET /operator/autopilot/configuration`
- [ ] `PUT /operator/autopilot/configuration`
- [ ] `GET /operator/autopilot/health`
- [ ] `GET /operator/autopilot/state`

#### `/operator/keyring`

- [ ] `GET /operator/keyring`
- [ ] `POST /operator/keyring`
- [ ] `PUT /operator/keyring`
- [ ] `DELETE /operator/keyring`

#### `/operator/license`

These endpoints will not be added as they require Consul Enterprise.

#### `/operator/raft`

- [ ] `GET /operator/raft/configuration`
- [ ] `DELETE /operator/raft/peer`

#### `/operator/segment`

These endpoints will not be added as they require Consul Enterprise.

### `/namespaces`

These endpoints will not be added as they require Consul Enterprise.

### `/query`

- [ ] `POST /query`
- [ ] `GET /query`
- [ ] `PUT /query/:uuid`
- [ ] `GET /query/:uuid`
- [ ] `DELETE /query/:uuid`
- [ ] `GET /query/:uuid/execute`
- [ ] `GET /query/:uuid/explain

### `/snapshot`

- [ ] `GET /snapshot`
- [ ] `PUT /snapshot`

### `/status`

- [ ] `GET /status/leader`
- [ ] `GET /status/peers`

### `/txn`

- [ ] `PUT /txn`
